import type { DemoProfile } from "@/lib/types";

export const demoProfile: DemoProfile = {
  id: "demo-profile",
  user_id: "demo-user",
  username: "demo-student",
  full_name: "Parth Shinge",
  profile_picture_url: "/parth-shinge.jpg",
  college: "D.Y. Patil Agri. & Technical Univ.",
  branch: "B.Tech – AI & Machine Learning",
  year: "Final Year (2023 - 2026)",
  bio: "Final-year AI/ML student with skills in data analytics and software development. Certified AI-Machine Learning Engineer by Maharashtra State Board, experienced in building data-driven ML models and interactive visual dashboards.",
  skills: [
    "Python",
    "SQL",
    "Power BI",
    "Tableau",
    "Scikit-learn",
    "TensorFlow",
    "Keras",
    "NLTK",
    "MySQL",
    "Git",
    "HTML",
    "CSS",
  ],
  github: "https://github.com/parthshinge",
  linkedin: "https://linkedin.com/in/parth-shinge",
  website: "https://github.com/parthshinge",
  twitter: "",
  wallet_address: "0x8B3c1d7B8c6D3e9dBf2BfeF0d5d3c47e2D9A1a10",
  internship_status: "AI-ML Intern at Vistara Labs, Inc.",
  ppo_status: "Completed Web Development Internship at Trichulin Business Ventures",
  stipend_status: "CGPA: 8.11 / 10.0",
  open_to_work: true,
  resume_url: "https://github.com/parthshinge/student-proof-of-work-web/raw/main/public/parth-shinge.jpg", // placeholder for resume link
  view_count: 2450,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  projects: [
    {
      id: "project-1",
      profile_id: "demo-profile",
      title: "Fetal Health Classification",
      description:
        "Built a multi-class classification model on 2,126 CTG records achieving 95.3% accuracy and 0.986 ROC-AUC; performed EDA using heatmaps, pair plots, and KDE analysis.",
      tech_stack: ["Python", "Scikit-learn", "Random Forest", "GridSearchCV"],
      github_url: "https://github.com/parthshinge",
      demo_url: "https://github.com/parthshinge",
      image_url: "/fetal-health.png",
    },
    {
      id: "project-2",
      profile_id: "demo-profile",
      title: "Sales Performance Dashboard",
      description:
        "Designed interactive Power BI dashboards analyzing historical sales data to identify growth trends and optimization opportunities supporting strategic decision-making.",
      tech_stack: ["Power BI", "Excel", "Data Analytics"],
      github_url: "https://github.com/parthshinge",
      demo_url: "https://github.com/parthshinge",
      image_url: "/sales-dashboard.png",
    },
    {
      id: "project-3",
      profile_id: "demo-profile",
      title: "Disease Classification System",
      description:
        "Developed a CNN-based model to classify 17 types of nail diseases from image data, using data augmentation and dropout techniques to improve generalization.",
      tech_stack: ["Python", "TensorFlow", "CNN", "Keras"],
      github_url: "https://github.com/parthshinge",
      demo_url: "https://github.com/parthshinge",
      image_url: "/disease-classification.png",
    },
    {
      id: "project-4",
      profile_id: "demo-profile",
      title: "Enquiry Chatbot",
      description:
        "Built an AI-powered chatbot using NLP to handle real-time user queries, implementing tokenization and NLTK to improve response accuracy.",
      tech_stack: ["Python", "ChatterBot", "NLTK", "NLP"],
      github_url: "https://github.com/parthshinge",
      demo_url: "https://github.com/parthshinge",
      image_url: "/chatbot.png",
    },
  ],
  proofs: [
    {
      id: "proof-1",
      profile_id: "demo-profile",
      title: "Microsoft Certified: Azure Fundamentals",
      type: "Course Certificate",
      image_url: "/azure-fundamentals.png",
    },
    {
      id: "proof-2",
      profile_id: "demo-profile",
      title: "AI-ML Engineer Certification - MSBTE",
      type: "Internship Certificate",
      image_url: "/aiml-engineer.png",
    },
  ],
};